version: '3'
services:
  postgres:
    image: 'postgres:13.1'
    restart: always
    ports:
      - 5432:5432
    # volumes:
    #   - ./infra-dump:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: infrauser
      POSTGRES_PASSWORD: cyklatillmorgonkaffetgudvagott
      POSTGRES_DB: infra-reveal
  # web:
  #   image: 'sebastianandreas/red-web:latest'
  #   restart: always
  #   ports:
  #     - 3000:3000
  # api:
  #   build: '.'
  #   restart: always
  #   ports:
  #     - 8765:8765
  #     - 4000:4000
  #   links:
  #     - postgres
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USERNAME: infrauser
  #     DB_PASSWORD: cyklatillmorgonkaffetgudvagott
  #     DB: infra-reveal
  #     COOKIE_SECRET: supersecret2
  proxy:
    build: './proxy/mitm'
    environment:
      WEBSOCKET_HOST: host.docker.internal
    # volumes:
    #   - /data:/tmp/mitm-proxy
    # privileged: true
    ports:
      - 8888:8888
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # pgadmin:
  #   image: 'dpage/pgadmin4:latest'
  #   links:
  #     - postgres
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: 'user@email.com'
  #     PGADMIN_DEFAULT_PASSWORD: 'password'
  #     PGADMIN_LISTEN_PORT: 8001
  #   ports:
  #     - 8001:8001
