version: '3'
services:
  caddy:
    image: 'appademin/red-caddy:latest'
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - web
      - api
      - mitmproxy
      - adminer
    volumes:
      - /data/caddy:/root/.caddy
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '50m'
  postgres:
    image: 'sebastianandreas/red-postgres:latest'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /mnt/db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: infrauser
      POSTGRES_PASSWORD: cyklatillmorgonkaffetgudvagott
      POSTGRES_DB: infra-reveal
  web:
    image: 'sebastianandreas/red-web:latest'
    restart: always
    ports:
      - 3000:3000
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '50m'
  api:
    image: 'sebastianandreas/red-api:latest'
    restart: always
    links:
      - postgres
    ports:
      - 8765:8765
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: infrauser
      DB_PASSWORD: cyklatillmorgonkaffetgudvagott
      DB: infra-reveal
      COOKIE_SECRET: supersecret2
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: skrivbordetförkaffepausen
      DIGITAL_OCEAN_TOKEN: 56cd20d1881c3d7a04f009d3b91e13050d1c6f1eab1e453df41c480e9188205c
      FIREWALL_ID: c80915da-464e-4697-ad4f-8878bea9724f
    command: npm run prod-start
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '50m'
  mitmproxy:
    image: 'sebastianandreas/red-mitm-python-proxy:latest'
    restart: always
    links:
      - api
    depends_on:
      - api
    ports:
      - 8888:8888
    environment:
      WEBSOCKET_HOST: api
    volumes:
      - /mnt/mitmproxy:/home/mitmproxy/.mitmproxy
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '50m'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres
    # environment:
    #   PGADMIN_DEFAULT_EMAIL: 'sebastian.andreasson@ait.gu.se'
    #   PGADMIN_DEFAULT_PASSWORD: 'mugglunchtilltangenbordet'
    #   PGADMIN_LISTEN_PORT: 8001
    # ports:
    #   - 8001:8001
