name: red-infra-reveal

static_sites:
  - name: web
    environment_slug: html
    build_command: npm run build
    github:
      repo: hci-gu/RED-infra-reveal
      branch: main
      deploy_on_push: true
    source_dir: web
    output_dir: /build
    index_document: index.html
    routes:
      - path: /

services:
  - name: api
    environment_slug: node-js
    build_command: npm run build-admin
    run_command: npm start
    github:
      repo: hci-gu/RED-infra-reveal
      branch: main
      deploy_on_push: true
    routes:
      - path: /api
